---
apiVersion: v1
kind: Secret
metadata:
  name: dk.example.com
data:
  # docker login -u kube -p kube
  # cat .docker/config.json | tr '\n' ' ' | tr '\t' ' ' | base64'
  .dockerconfigjson: eyAgImF1dGhzIjogeyAgICJkay5keW5hY29tbWVyY2VsYWIuY29tIjogeyAgICAiYXV0aCI6ICJhM1ZpWlRwcmRXSmxNVEl6IiAgIH0gIH0sICAiSHR0cEhlYWRlcnMiOiB7ICAgIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy44IChsaW51eCkiICB9IH0=
type: kubernetes.io/dockerconfigjson
